---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: centos-7.0
  - name: debian-7.7
  - name: fedora-23
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
- name: default
  run_list:
  - recipe[xvfb_test]
