---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12
  chef_license: accept

platforms:
  - name: centos-7.1
  - name: ubuntu-16.04

suites:
- name: default
  run_list:
  - xvfb
